apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
  - ../base/monitor/production
  - https://github.com/konflux-ci/release-service/config/default?ref=51f40986697440170195e8e0872bd60d3c531e98

components:
  - ../k-components/manager-resources-patch

images:
  - name: quay.io/konflux-ci/release-service
    newName: quay.io/konflux-ci/release-service
    newTag: 51f40986697440170195e8e0872bd60d3c531e98

namespace: release-service
