apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
  - ../base/monitor/production
  - https://github.com/konflux-ci/release-service/config/default?ref=95fae338c34e5753a979d2ef79157978c06e8823

components:
  - ../k-components/manager-resources-patch

images:
  - name: quay.io/konflux-ci/release-service
    newName: quay.io/konflux-ci/release-service
    newTag: 95fae338c34e5753a979d2ef79157978c06e8823

namespace: release-service
